#The service
services:
  #The service name
  nextjs:
    #Build from where
    build:
      context: .
      dockerfile: Dockerfile.background
    #Exposed port
    ports:
      - "5555:5555"
    #env vars if you need
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data